# .gitpod.yml

# Define the image to use (a common choice for Python projects)
image: python:3.11

# List of ports to open and their configurations
ports:
  - port: 8000
    onOpen: open-preview # Opens the Django server in the GitPod preview panel
    name: Django Server
    description: The main Django development server

# Tasks to run when the workspace starts
tasks:
  - name: Setup & Run Server
    # Initialize the project setup
    init: |
      pip install --upgrade pip
      pip install django djangorestframework django-environ dj-rest-auth django-allauth requests
      
      # NOTE: Assuming you have already run 'django-admin startproject' and 'python manage.py startapp'
      # and the .env file is present for keys.
      
      # 1. Run migrations
      python manage.py makemigrations core
      python manage.py migrate
      
      # 2. Inform the user to create a superuser if they haven't already
      echo "--- SETUP COMPLETE ---"
      echo "Remember to run 'python manage.py createsuperuser' in a new terminal if this is the first time."
      echo "--- STARTING SERVER ---"
      
    # Command to execute after initialization (runs the server)
    command: python manage.py runserver 0.0.0.0:8000
